### ISSUE TITLE
Add a confirmation dialog?

### ISSUE THREAD

**Issue by baskerville** [geek1011/NickelMenu#13]
I thought it might be useful to have a confirmation dialog with at least two buttons.

Maybe the *cancel dialog* that shows up in the output of: `arm-linux-gnueabihf-objdump -T libnickel.so | grep -i 'confirm.*show.*dialog'` (that is `_ZN25ConfirmationDialogFactory16showCancelDialogERK7QStringS2_`) could fulfill this task?

**Comment by geek1011** [comment]
Yes, that would be the right symbol. The main difficulty is that it uses signals, which are a PITA to use with dlsym, as they require functional vtables, Qt metaobjects, and would-be-generated-by-moc names. Due to this, they are also the most likely to break in unexpected ways in the future. If there's any alternative, I'd rather do that instead.

Some random ideas:
- A custom dialog completely independent from libnickel (this way, we at least control the vtables and can generate the metaobject, but then we have to handle the touch input, which is another PITA).
- There might be a non-async dialog somewhere (I'll look at this after v0.0.2).

**Comment by geek1011** [comment]
I've decided against implementing this for now, but may reconsider it in the future if the need arises.
